version: '3.8'

services:
    app:
        image: php:8.1-fpm
        container_name: laravel-app
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - app-network
        depends_on:
            - db
        ports:
            - "8080:82"
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=secret
            - CACHE_DRIVER=redis
            - QUEUE_CONNECTION=rabbitmq
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD=null
            - REDIS_DB=0
        command: sh -c "while ! nc -z db 3306; do sleep 1; done; php artisan migrate --force && php-fpm"

    db:
        image: mysql:8.0
        container_name: mysql-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
        networks:
            - app-network
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    nginx:
        image: nginx:alpine
        container_name: nginx_laravel
        ports:
            - "8082:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        depends_on:
            - app
        networks:
            - app-network

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge

volumes:
    mysql_data:
        driver: local
